version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: spring_docker_db
    environment:
      POSTGRES_DB: spring_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
